### ISSUE TITLE
Add new authetication support

### ISSUE THREAD

**Issue by ecarreras** [gisce/empowering#15]
Implemented in #17

**Comment by bmiro** [comment]
Crec que hi ha un problema d'expiració de sessions amb l'autenticació.

Al cap de un temps (no gaires hores) el worker/erp que ha obert una connexió amb empowering si es fan peticions a través d'ell passa a donar errors 401. Si es reinicia torna a funcionar correctament.

Per el que van comentar els de CIMNE tal vegada és un problema de sessions.

**Comment by ecarreras** [comment]
Ostres, a la API no veig cap mecanisme de renovar la sessió, però crec que ells haurien de mirar l'activitat d'una sessió i no expirar-la si hi ha activat. Què creus tu?

Per això moltes APIs no treballen amb sessió i a cada petició s'envia un *token*. Obres un ticket amb això o vols que implementi que si ja hi ha token i en una petició retorna un `401` provi de tornar a fer login?

**Comment by bmiro** [comment]
La veritat és que m'estim més que ho implementis tu ;)

Tal vegada amb un try except a la part més interna que retorni el 401 bastaria per controlar-ho.

Iguament els hi obriré un ticket.

**Comment by ecarreras** [comment]
Ok, demà estarà llest que avui estaré fora de l'oficina tot el dia

**Comment by ecarreras** [comment]
@bmiro ja està implementat si ho vols provar, he fet un test que he posat a la mateix PR
